CREATE DATABASE library;  

USE library;

CREATE TABLE AUTHORS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAMA VARCHAR(100) NOT NULL
);

CREATE TABLE BOOKS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ISBN VARCHAR(13),
	TITLE VARCHAR(100) NOT NULL,
	AUTHOR_ID INT,  
	FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID)  
);                                                -- NOMOR 1

ALTER TABLE authors
ADD NATIONALITY VARCHAR(50);                      -- NOMOR 2

ALTER TABLE BOOKS
ADD CONSTRAINT UNIQUE (ISBN);                     -- NOMOR 3

DESCRIBE AUTHORS;
DESCRIBE BOOKS;                                   -- NOMOR 4

CREATE TABLE MEMBERS (                            -- NOMOR 5
	ID INT PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	EMAIL VARCHAR(100) UNIQUE,
	PHONE_NUMBER CHAR(10) NULL,
	JOIN_DATE DATE, 
	MEMBERSHIP_TYPE VARCHAR(50)
)                                                 -- membuat tabel members

ALTER TABLE BOOKS
MODIFY TITLE VARCHAR(150);

ALTER TABLE BOOKS
ADD PUBLISHED_YEAR YEAR,
ADD GENRE VARCHAR(50),
ADD COPIES_AVAILABLE INT;                         -- menambahkan variabel baru ke books

CREATE TABLE BORROWINGS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	MEMBER_ID INT,
	BOOK_ID INT,
	BORROW_DATE DATE,
	RETURN_DATE DATE NULL,
	FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(ID),
	FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(ID)      -- membuat tabel borrowings
)

DROP TABLE IF EXISTS BORROWINGS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS authors;                     -- menghapus tabel untuk menguji soal satu per satu



	